CREATE TABLE public.clientes (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar NOT NULL,
	email varchar NOT NULL,
	cpf varchar NOT NULL,
	telefone varchar NOT NULL,
	cep varchar NULL,
	logradouro varchar NULL,
	bairro varchar NULL,
	cidade varchar NULL,
	complemento varchar NULL,
	ponto_referencia varchar NULL,
	CONSTRAINT clientes_pk PRIMARY KEY (id)
);
